import type { LocalizedText } from './i18n';

export type Permissioning = 'permissionless' | 'hybrid' | 'permissioned' | 'n/a';
export type ClientDiversityStatus = 'single' | 'multi' | 'n/a';

export interface ValidatorEntry {
  readonly name: string;
  readonly stakeSharePct: number;
}

export interface DecentralizationData {
  readonly chainId: string;
  readonly nakamotoCoefficient: number | null;
  readonly nakamotoNote?: LocalizedText;
  readonly activeValidators: number | null;
  readonly validatorCap: number | null;
  readonly minStake: LocalizedText;
  readonly permissioning: Permissioning;
  readonly top33SharePct: number | null;
  readonly clientDiversity: ClientDiversityStatus;
  readonly clientDiversityNote?: LocalizedText;
  readonly topValidators?: readonly ValidatorEntry[];
  readonly notes?: LocalizedText;
  readonly lastUpdated: string;
  readonly sourceUrls?: readonly string[];
}

export const DECENTRALIZATION: readonly DecentralizationData[] = [
  {
    chainId: 'ethereum',
    nakamotoCoefficient: 350_000,
    nakamotoNote: {
      ko: '검증자 수 기준. 모든 validator가 32 ETH 동일 가중치를 가지므로 NC = 활성 validator 수의 ⅓ (~1.05M의 1/3). 스테이킹 풀 지분(Lido ~28%, Coinbase, Binance 등)을 하나의 엔티티로 묶으면 훨씬 낮은 값이 보고되기도 하지만, Lido는 DAO 거버넌스 하에 다수의 독립 노드 운영자가 키를 운영하는 구조라 단일 공격 주체로 간주하기 어렵다는 반론이 있습니다.',
      en: 'By validator count. All validators share an equal 32 ETH weight, so NC ≈ one-third of active validators (~1.05M / 3). When staking pool shares (Lido ~28%, Coinbase, Binance, etc.) are aggregated as single entities, much lower numbers are sometimes reported, but Lido is a DAO-governed protocol where many independent node operators hold the keys, so treating it as a single attacker is itself contested.',
    },
    activeValidators: 1_050_000,
    validatorCap: null,
    minStake: { ko: '32 ETH (Pectra 이후 최대 2048 ETH 압축)', en: '32 ETH (up to 2048 ETH post-Pectra)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'multi',
    clientDiversityNote: {
      ko: 'Execution: Geth, Nethermind, Besu, Erigon, Reth / Consensus: Prysm, Lighthouse, Teku, Nimbus, Lodestar, Grandine',
      en: 'Execution: Geth, Nethermind, Besu, Erigon, Reth / Consensus: Prysm, Lighthouse, Teku, Nimbus, Lodestar, Grandine',
    },
    notes: {
      ko: 'Lido는 30개+ 독립 노드 운영자와 DAO 거버넌스로 운영되므로 점유율이 높다고 해서 바로 단일 공격 주체가 되지는 않습니다. 다만 Lido DAO의 거버넌스 캡처, 지배적 LST의 시장 리스크(e.g., stETH 페그), 대형 CEX 운영자 집중 등은 여전히 유의미한 중앙화 벡터로 논의됩니다.',
      en: 'Lido operates with 30+ independent node operators under DAO governance, so a high share does not automatically make it a single attacker. That said, governance capture of the Lido DAO, market risks of a dominant LST (e.g., stETH peg), and concentration among large CEX operators remain meaningful centralization vectors.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.rated.network/', 'https://beaconcha.in/'],
  },
  {
    chainId: 'bnb',
    nakamotoCoefficient: 7,
    activeValidators: 41,
    validatorCap: 45,
    minStake: { ko: '자체 본딩 최소 10,000 BNB, 선출되려면 ~20K+ BNB 필요', en: 'Min self-bond 10,000 BNB; ~20K+ BNB typically required to be elected' },
    permissioning: 'hybrid',
    top33SharePct: 40,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'BSC Geth 포크 단일 클라이언트', en: 'Single BSC Geth fork' },
    notes: {
      ko: '41개의 active 검증자 + 24개 standby (총 캡 45). 대형 거래소와 바이낸스 연관 운영자가 상당 부분을 점유.',
      en: '41 active validators + standby set (cap 45). Large exchanges and Binance-affiliated operators hold a significant share.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.bnbchain.org/bnb-smart-chain/validator/overview/'],
  },
  {
    chainId: 'solana',
    nakamotoCoefficient: 20,
    activeValidators: 1500,
    validatorCap: null,
    minStake: { ko: '규정상 없음 (투표 수수료 ~1 SOL/day, 실질적으로 고성능 하드웨어 필요)', en: 'No hard minimum; vote fees ~1 SOL/day; high-end hardware effectively required' },
    permissioning: 'permissionless',
    top33SharePct: 33,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'Agave (구 Solana Labs), Jito-Solana, Firedancer (Frankendancer 포함)', en: 'Agave (formerly Solana Labs), Jito-Solana, Firedancer (incl. Frankendancer)' },
    topValidators: [
      { name: 'Figment', stakeSharePct: 3.54 },
      { name: 'Helius', stakeSharePct: 3.34 },
      { name: 'binance staking', stakeSharePct: 2.98 },
      { name: 'Jupiter', stakeSharePct: 2.87 },
      { name: 'Ledger by Figment', stakeSharePct: 2.04 },
      { name: 'Everstake', stakeSharePct: 1.73 },
      { name: 'Bitwise Onchain Solutions', stakeSharePct: 1.7 },
      { name: 'Forward Industries', stakeSharePct: 1.65 },
      { name: 'Galaxy', stakeSharePct: 1.58 },
      { name: 'Staking Facilities | MEV 🔥', stakeSharePct: 1.54 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.validators.app/', 'https://docs.anza.xyz/', 'https://nakaflow.io/'],
  },
  {
    chainId: 'tron',
    nakamotoCoefficient: 5,
    activeValidators: 27,
    validatorCap: 27,
    minStake: { ko: '득표 기반 (스테이킹이 아닌 TRX freeze 투표)', en: 'Vote-based (TRX freeze for votes, not staking)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Poloniex', stakeSharePct: 9.01 },
      { name: 'TRONALLIANCE', stakeSharePct: 7.18 },
      { name: 'Abra Capital Management', stakeSharePct: 6.51 },
      { name: 'Crypto Labs', stakeSharePct: 6.42 },
      { name: 'BlockAnalysis', stakeSharePct: 5.43 },
      { name: 'Binance Staking', stakeSharePct: 5.14 },
      { name: 'HTX.COM', stakeSharePct: 4.85 },
      { name: 'JD Investment', stakeSharePct: 4.41 },
      { name: 'Intelligence Quant', stakeSharePct: 3.93 },
      { name: 'Crypto Innovation Fund', stakeSharePct: 3.85 },
    ],
    notes: {
      ko: 'DPoS. 상위 27개 SR만 블록 생성. 후보 127개 중 상위 127은 "Partner"로서 candidate로 남지만 BP는 27개.',
      en: 'DPoS. Only the top 27 SRs produce blocks. The remaining top-127 remain as candidates but do not produce blocks.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://tronscan.org/#/data/stats3'],
  },
  {
    chainId: 'provenance',
    nakamotoCoefficient: 8,
    activeValidators: 60,
    validatorCap: 100,
    minStake: { ko: '본딩 스테이크로 상위 N에 진입 (dynamic)', en: 'Dynamic threshold to enter top N by bonded stake' },
    permissioning: 'permissionless',
    top33SharePct: 45,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Figment', stakeSharePct: 5.5 },
      { name: 'Figure', stakeSharePct: 5.49 },
      { name: 'Blockdaemon', stakeSharePct: 5.18 },
      { name: 'NUVA Labs', stakeSharePct: 4.39 },
      { name: 'Radix', stakeSharePct: 4.24 },
      { name: 'Osetra', stakeSharePct: 4.16 },
      { name: 'NUVA Labs 2', stakeSharePct: 4.14 },
      { name: 'Little Resonance', stakeSharePct: 4.06 },
      { name: 'Cosmostation', stakeSharePct: 4.02 },
      { name: 'MP Validator One', stakeSharePct: 3.73 },
    ],
    notes: {
      ko: '금융 기관 특화 L1으로 Figure 계열 기관의 검증자 비중이 높아 상대적으로 집중된 검증자 세트.',
      en: 'Institution-focused L1; Figure-affiliated operators hold a significant share, making the validator set relatively concentrated.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://explorer.provenance.io/validators'],
  },
  {
    chainId: 'hyperliquid',
    nakamotoCoefficient: 3,
    activeValidators: 21,
    validatorCap: null,
    minStake: { ko: '~10K HYPE 본딩 + 위임 필요', en: '~10K HYPE self-bond + delegations required' },
    permissioning: 'hybrid',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Hyper Foundation 2', stakeSharePct: 13.24 },
      { name: 'Hyper Foundation 3', stakeSharePct: 12.95 },
      { name: 'Hyper Foundation 1', stakeSharePct: 12.44 },
      { name: 'Hyper Foundation 4', stakeSharePct: 12.36 },
      { name: 'Anchorage By Figment', stakeSharePct: 8.14 },
      { name: 'Nansen x HypurrCollective', stakeSharePct: 5.71 },
      { name: 'Hypurrscanning', stakeSharePct: 5.43 },
      { name: 'infinitefield.xyz', stakeSharePct: 4.48 },
      { name: 'Hyper Foundation 5', stakeSharePct: 3.5 },
      { name: 'HyperStake', stakeSharePct: 2.81 },
    ],
    notes: {
      ko: '2024년 메인넷 이후 21개 validator로 시작, 점진적으로 확장 중. 팀/공동창업자 연관 노드가 초기 스테이크의 상당 부분을 차지.',
      en: 'Since 2024 mainnet, started with 21 validators and expanding gradually. Team/cofounder-affiliated nodes hold a significant share of the early stake.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://hyperliquid.gitbook.io/hyperliquid-docs/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'polygon',
    nakamotoCoefficient: 4,
    activeValidators: 100,
    validatorCap: 105,
    minStake: { ko: '~100K POL 셀프 스테이크 + 위임', en: '~100K POL self-stake + delegations' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Upbit Staking', stakeSharePct: 11.07 },
      { name: 'Coinbase', stakeSharePct: 9.55 },
      { name: 'Luganodes', stakeSharePct: 9.31 },
      { name: 'Binance Node', stakeSharePct: 6.89 },
      { name: 'Figment', stakeSharePct: 6.16 },
      { name: 'Matic Power', stakeSharePct: 5.68 },
      { name: '0x203847fb', stakeSharePct: 5.01 },
      { name: 'Blockdaemon', stakeSharePct: 4.81 },
      { name: 'Kraken', stakeSharePct: 4.13 },
      { name: 'Kiln x Ownest 🔸 Pro Staking 🔸', stakeSharePct: 3.58 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://staking.polygon.technology/', 'https://nakaflow.io/'],
  },
  {
    chainId: 'avalanche',
    nakamotoCoefficient: 26,
    activeValidators: 1200,
    validatorCap: null,
    minStake: { ko: '2,000 AVAX (검증자), 25 AVAX (위임)', en: '2,000 AVAX (validator) or 25 AVAX (delegator)' },
    permissioning: 'permissionless',
    top33SharePct: 32,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'AvalancheGo 단일 (Coreth 서브컴포넌트)', en: 'Single AvalancheGo (Coreth subcomponent)' },
    topValidators: [
      { name: 'Node a3Pp8p2wSe', stakeSharePct: 1.57 },
      { name: 'Node ggu8pfz2Kv', stakeSharePct: 1.57 },
      { name: 'Node T1e8oxwRnF', stakeSharePct: 1.57 },
      { name: 'Node PLLFaNQjin', stakeSharePct: 1.57 },
      { name: 'Node qSC9rTgZeJ', stakeSharePct: 1.56 },
      { name: 'Node iccY5zVEWA', stakeSharePct: 1.51 },
      { name: 'Node 9f1q3tTjT5', stakeSharePct: 1.51 },
      { name: 'Node KuE814SAVM', stakeSharePct: 1.51 },
      { name: 'Node EnC72iu9Gh', stakeSharePct: 1.43 },
      { name: 'Node fSFsYh4faj', stakeSharePct: 1.41 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.avax.network/about/blog/decentralization', 'https://subnets.avax.network/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'sui',
    nakamotoCoefficient: 18,
    activeValidators: 113,
    validatorCap: null,
    minStake: { ko: '30M SUI (현재 요구 · 커뮤니티 위임 포함)', en: '30M SUI (current requirement, incl. delegation)' },
    permissioning: 'permissionless',
    top33SharePct: 30,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'sui-node 단일 구현 (Rust)', en: 'Single sui-node (Rust)' },
    topValidators: [
      { name: 'Mysten-1', stakeSharePct: 2.82 },
      { name: 'Mysten-2', stakeSharePct: 2.51 },
      { name: 'Luganodes', stakeSharePct: 2.44 },
      { name: 'Blockdaemon', stakeSharePct: 2.13 },
      { name: 'Galaxy Digital', stakeSharePct: 2.01 },
      { name: 'Chorus One', stakeSharePct: 1.92 },
      { name: 'Aftermath', stakeSharePct: 1.92 },
      { name: 'Coinbase', stakeSharePct: 1.83 },
      { name: 'Figment', stakeSharePct: 1.77 },
      { name: 'DSRV', stakeSharePct: 1.71 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://suivision.xyz/validators', 'https://docs.sui.io/concepts/tokenomics', 'https://nakaflow.io/'],
  },
  {
    chainId: 'monad',
    nakamotoCoefficient: 24,
    activeValidators: 40,
    validatorCap: 100,
    minStake: { ko: '초기 초청 검증자 (구체 스테이크 미공개)', en: 'Invited validators at launch (stake requirement not public)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: '2025년 말 메인넷. 초기 검증자 세트는 초청제이며 퍼미션리스 확장 로드맵 진행 중.',
      en: 'Mainnet late 2025. Initial validator set is invited, with a roadmap toward permissionless expansion.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.monad.xyz/', 'https://nakaflow.io/'],
  },
  {
    chainId: 'cronos',
    nakamotoCoefficient: 4,
    activeValidators: 30,
    validatorCap: 30,
    minStake: { ko: '본딩 스테이크로 상위 30에 진입 (dynamic)', en: 'Dynamic threshold to enter top 30 by bonded stake' },
    permissioning: 'permissionless',
    top33SharePct: 45,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Pioneer 11', stakeSharePct: 9.8 },
      { name: 'Huygens', stakeSharePct: 9.8 },
      { name: 'Voyager 1', stakeSharePct: 9.8 },
      { name: 'Voyager 2', stakeSharePct: 9.8 },
      { name: 'fulcrom node', stakeSharePct: 7.41 },
      { name: 'minted node', stakeSharePct: 7.41 },
      { name: 'veno node', stakeSharePct: 7.41 },
      { name: 'vvs node', stakeSharePct: 7.41 },
      { name: 'ferro node', stakeSharePct: 7.41 },
      { name: 'tectonic node', stakeSharePct: 7.41 },
    ],
    notes: {
      ko: 'Cronos Labs 관련 노드가 상당 부분을 점유하여 NC가 낮음.',
      en: 'Cronos Labs-affiliated nodes hold a significant share, keeping NC low.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://crypto.org/explorer/validators'],
  },
  {
    chainId: 'aptos',
    nakamotoCoefficient: 15,
    activeValidators: 150,
    validatorCap: null,
    minStake: { ko: '1M APT (셀프 본딩 기준 진입 임계치)', en: '1M APT (self-bond threshold to enter set)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'aptos-core (Rust) 단일', en: 'Single aptos-core (Rust)' },
    topValidators: [
      { name: '0x..1510c218', stakeSharePct: 3.3 },
      { name: '0x..c97682de', stakeSharePct: 3.24 },
      { name: '0x..0c884af5', stakeSharePct: 3.24 },
      { name: '0x..1a4a4393', stakeSharePct: 2.61 },
      { name: '0x..b9f551e8', stakeSharePct: 2.54 },
      { name: '0x..8521f5dd', stakeSharePct: 2.26 },
      { name: '0x..01cef6ec', stakeSharePct: 2.19 },
      { name: '0x..cc650679', stakeSharePct: 1.98 },
      { name: '0x..2691404a', stakeSharePct: 1.95 },
      { name: '0x..bd1b33ba', stakeSharePct: 1.87 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://explorer.aptoslabs.com/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'stellar',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: 'SCP(FBA)는 지분 기반이 아니므로 전통적 Nakamoto Coefficient 정의가 적용되지 않음.',
      en: 'SCP (FBA) is not stake-based, so the traditional Nakamoto Coefficient definition does not apply.',
    },
    activeValidators: 80,
    validatorCap: null,
    minStake: { ko: '해당 없음 (스테이킹 없음)', en: 'N/A (no staking)' },
    permissioning: 'n/a',
    top33SharePct: null,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'Stellar Core · horizon (공식 구현)', en: 'Stellar Core and Horizon (official implementations)' },
    notes: {
      ko: 'Quorum Slice 기반 신뢰 모델. 활성 검증자 중 SDF 직접/간접 관할 노드 비중이 유의미함.',
      en: 'Quorum-slice trust model. A meaningful share of active validators is directly or indirectly operated by SDF.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://stellarbeat.io/'],
  },
  {
    chainId: 'movement',
    nakamotoCoefficient: 2,
    activeValidators: 100,
    validatorCap: null,
    minStake: { ko: '초기 초청 검증자 (구체 수치 미공개)', en: 'Invited validators at launch (requirement not public)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    topValidators: [
      { name: '54afb644c7', stakeSharePct: 25.39 },
      { name: '9f9d901f1f', stakeSharePct: 24.96 },
      { name: 'dd0b4b76ea', stakeSharePct: 24.84 },
      { name: '2b85008b9c', stakeSharePct: 24.8 },
    ],
    notes: {
      ko: 'Aptos와 동일한 DiemBFT 계보. 초기 검증자 세트는 초청제.',
      en: 'Same DiemBFT lineage as Aptos. Initial validator set is invited.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.movementnetwork.xyz/'],
  },
  {
    chainId: 'cardano',
    nakamotoCoefficient: 57,
    activeValidators: 3000,
    validatorCap: null,
    minStake: { ko: '스테이크 풀 운영: 500 ADA 보증금 + pledge. 위임: 제한 없음', en: 'Pool operator: 500 ADA deposit + pledge. Delegation: no minimum' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'cardano-node (Haskell), Jormungandr (deprecated)', en: 'cardano-node (Haskell), Jormungandr (deprecated)' },
    topValidators: [
      { name: 'ADV', stakeSharePct: 0.72 },
      { name: 'CH1', stakeSharePct: 0.71 },
      { name: 'ADALO', stakeSharePct: 0.71 },
      { name: 'ADV3', stakeSharePct: 0.71 },
      { name: 'BLADE', stakeSharePct: 0.71 },
      { name: '1PCT0', stakeSharePct: 0.7 },
      { name: 'SPIRE', stakeSharePct: 0.69 },
      { name: 'TITAN', stakeSharePct: 0.69 },
      { name: 'pool1vx9tzlkgafernd9', stakeSharePct: 0.68 },
      { name: 'PILOT', stakeSharePct: 0.67 },
    ],
    notes: {
      ko: '3000+개의 스테이크 풀, 풀 운영자가 saturation 메커니즘으로 인위적 중앙화 방지. NC는 기업·거래소 풀 집계 기준.',
      en: '3000+ stake pools, with saturation mechanism preventing artificial centralization. NC reflects corporate/exchange pool aggregation.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://pooltool.io/', 'https://nakaflow.io/'],
  },
  {
    chainId: 'stacks',
    nakamotoCoefficient: 4,
    activeValidators: 70,
    validatorCap: null,
    minStake: { ko: 'Signer: ~100K+ STX stacking 필요', en: 'Signers need ~100K+ STX stacked' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'f32640bc8169', stakeSharePct: 12.29 },
      { name: '7ed8e5cfb4f3', stakeSharePct: 10.15 },
      { name: 'd1e4105437b7', stakeSharePct: 8.31 },
      { name: 'c13497caec6e', stakeSharePct: 8.3 },
      { name: 'c0b789eae91a', stakeSharePct: 8.23 },
      { name: 'bf751bf82555', stakeSharePct: 7.88 },
      { name: 'a76eb3f86d2f', stakeSharePct: 6.86 },
      { name: '40d06e8fe220', stakeSharePct: 6.29 },
      { name: '7ee8af5da202', stakeSharePct: 5.49 },
      { name: '8fe14941adce', stakeSharePct: 2.82 },
    ],
    notes: {
      ko: 'Nakamoto 업그레이드(2024) 이후 signer 세트가 블록 확정에 참여. Signer 수는 stacking 참여에 따라 변동.',
      en: 'Since the Nakamoto upgrade (2024), a signer set participates in block finalization. Signer count varies with stacking participation.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.stacks.co/'],
  },
  {
    chainId: 'near',
    nakamotoCoefficient: 9,
    activeValidators: 100,
    validatorCap: 100,
    minStake: { ko: '동적 seat price (현재 ~67K NEAR)', en: 'Dynamic seat price (~67K NEAR currently)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'nearcore (Rust) 단일', en: 'Single nearcore (Rust)' },
    topValidators: [
      { name: 'bisontrails2.poolv1.near', stakeSharePct: 5.05 },
      { name: 'figment.poolv1.near', stakeSharePct: 4.93 },
      { name: 'astro-stakers.poolv1.near', stakeSharePct: 4.63 },
      { name: 'binancenode1.poolv1.near', stakeSharePct: 4.02 },
      { name: 'bitwise_1.poolv1.near', stakeSharePct: 3.41 },
      { name: 'ledgerbyfigment.poolv1.near', stakeSharePct: 3.35 },
      { name: 'zavodil.poolv1.near', stakeSharePct: 3.33 },
      { name: 'sumerian.poolv1.near', stakeSharePct: 3.08 },
      { name: 'kiln-1.poolv1.near', stakeSharePct: 2.42 },
      { name: 'liver.pool.near', stakeSharePct: 2.06 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://near.org/validators/', 'https://near-nodes.io/'],
  },
  {
    chainId: 'dydx',
    nakamotoCoefficient: 6,
    activeValidators: 60,
    validatorCap: 60,
    minStake: { ko: '본딩 스테이크로 상위 60 진입 (dynamic)', en: 'Dynamic threshold to enter top 60' },
    permissioning: 'permissionless',
    top33SharePct: 33,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Polychain dYdX', stakeSharePct: 12.98 },
      { name: 'polkachu.com', stakeSharePct: 5.34 },
      { name: 'Keplr', stakeSharePct: 5.19 },
      { name: 'BinanceNode', stakeSharePct: 5.09 },
      { name: 'Cosmostation', stakeSharePct: 3.89 },
      { name: 'Kiln', stakeSharePct: 3.87 },
      { name: ' RHINO 🦏', stakeSharePct: 3.76 },
      { name: 'CLC', stakeSharePct: 3.64 },
      { name: 'TTT VN', stakeSharePct: 3.62 },
      { name: 'Chorus One', stakeSharePct: 3.6 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/dydx/validators'],
  },
  {
    chainId: 'gnosis',
    nakamotoCoefficient: 57_000,
    nakamotoNote: {
      ko: '검증자 수 기준. Ethereum과 동일한 Gasper로 각 validator가 동일 가중치(1 mGNO)를 가지므로 NC = 활성 validator 수의 ⅓ (~170K의 1/3).',
      en: 'By validator count. Uses the same Gasper as Ethereum where each validator has an equal weight (1 mGNO), so NC ≈ one-third of active validators (~170K / 3).',
    },
    activeValidators: 170000,
    validatorCap: null,
    minStake: { ko: '1 mGNO (= 0.032 GNO) + 1 GNO deposit', en: '1 mGNO (= 0.032 GNO) + 1 GNO deposit' },
    permissioning: 'permissionless',
    top33SharePct: null,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'Ethereum 클라이언트 호환 (Prysm, Lighthouse, Teku, Nethermind, Erigon 등)', en: 'Ethereum client-compatible (Prysm, Lighthouse, Teku, Nethermind, Erigon, etc.)' },
    lastUpdated: '2026-04',
    sourceUrls: ['https://beacon.gnosischain.com/'],
  },
  {
    chainId: 'kava',
    nakamotoCoefficient: 2,
    activeValidators: 75,
    validatorCap: 100,
    minStake: { ko: '본딩 스테이크로 상위 100 진입 (dynamic)', en: 'Dynamic threshold to enter top 100' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Kraken01', stakeSharePct: 26.53 },
      { name: 'Luganodes', stakeSharePct: 20.39 },
      { name: 'Cosmostation', stakeSharePct: 8.73 },
      { name: '0% Fee to TOP #1 🥇 | melea.xyz ◎', stakeSharePct: 6.42 },
      { name: 'Allnodes', stakeSharePct: 3.64 },
      { name: 'ChainLayer', stakeSharePct: 3.55 },
      { name: 'Everstake', stakeSharePct: 3.48 },
      { name: 'WeStaking', stakeSharePct: 3.42 },
      { name: 'HbStaking', stakeSharePct: 3.13 },
      { name: 'polkachu.com', stakeSharePct: 1.98 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/kava/validators'],
  },
  {
    chainId: 'berachain',
    nakamotoCoefficient: null,
    activeValidators: 69,
    validatorCap: 69,
    minStake: { ko: '250K BGT 본딩 + BERA 위임', en: '250K BGT self-bond + BERA delegation' },
    permissioning: 'permissionless',
    top33SharePct: 45,
    clientDiversity: 'single',
    notes: {
      ko: 'CometBFT 포크 BeaconKit 사용. Proof-of-Liquidity로 BGT 투표권과 스테이크가 분리된 구조.',
      en: 'Uses BeaconKit (CometBFT fork). Proof-of-Liquidity separates BGT voting power from stake.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.berachain.com/'],
  },
  {
    chainId: 'sei',
    nakamotoCoefficient: 7,
    activeValidators: 30,
    validatorCap: 30,
    minStake: { ko: '본딩 스테이크로 상위 30 진입 (dynamic)', en: 'Dynamic threshold to enter top 30' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Chorus One', stakeSharePct: 7.51 },
      { name: 'kingnodes 👑', stakeSharePct: 5.0 },
      { name: 'Everstake', stakeSharePct: 4.83 },
      { name: ' RHINO 🦏', stakeSharePct: 4.8 },
      { name: 'polkachu.com', stakeSharePct: 4.0 },
      { name: 'Anchorage Digital', stakeSharePct: 3.86 },
      { name: 'STAKEME', stakeSharePct: 3.76 },
      { name: 'sei0', stakeSharePct: 3.72 },
      { name: 'One Node', stakeSharePct: 3.58 },
      { name: ' Lavender.Five Nodes 🐝', stakeSharePct: 3.46 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/sei/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'hedera',
    nakamotoCoefficient: 9,
    nakamotoNote: {
      ko: 'Permissioned council이지만 HBAR 홀더가 council 노드에 위임 가능. Nakaflow는 위임 스테이크 분포 기준으로 NC를 11로 측정.',
      en: 'Permissioned council but HBAR holders can delegate to council nodes; Nakaflow measures NC by delegated-stake distribution at 11.',
    },
    activeValidators: 31,
    validatorCap: 39,
    minStake: { ko: 'Council 초대제 (Google, IBM, Standard Bank 등)', en: 'Council invitation (Google, IBM, Standard Bank, etc.)' },
    permissioning: 'permissioned',
    top33SharePct: null,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Hosted by LG | Singapore', stakeSharePct: 4.12 },
      { name: 'Node 1', stakeSharePct: 4.12 },
      { name: 'Hosted by Nomura | Tokyo, Japan', stakeSharePct: 4.12 },
      { name: 'Node 5', stakeSharePct: 4.12 },
      { name: 'Hosted by DLA Piper | Helsinki, Finland', stakeSharePct: 4.12 },
      { name: 'Hosted by Tata Communications | Frankfurt, Germany', stakeSharePct: 4.12 },
      { name: 'Hosted by IBM | Texas, USA', stakeSharePct: 4.12 },
      { name: 'Hosted by Deutsche Telekom | Berlin, Germany', stakeSharePct: 4.12 },
      { name: 'Hosted by Australian Payments Plus | Sydney, Australia', stakeSharePct: 4.12 },
      { name: 'Hosted by EDF | Paris, France', stakeSharePct: 4.12 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://hedera.com/council', 'https://nakaflow.io/'],
  },
  {
    chainId: 'ton',
    nakamotoCoefficient: null,
    activeValidators: 350,
    validatorCap: null,
    minStake: { ko: '~340K TON (Elector 컨트랙트 동적 임계치)', en: '~340K TON (dynamic threshold via Elector contract)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    lastUpdated: '2026-04',
    sourceUrls: ['https://tonscan.org/validators'],
  },
  {
    chainId: 'xrpl',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: 'UNL 기반 non-staking 합의. Nakamoto Coefficient 개념 미적용.',
      en: 'UNL-based non-staking consensus; the Nakamoto Coefficient concept does not apply.',
    },
    activeValidators: 35,
    validatorCap: null,
    minStake: { ko: '해당 없음 (UNL 등록만 필요)', en: 'N/A (UNL inclusion only)' },
    permissioning: 'n/a',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: 'Ripple, XRPLF, 대학 및 개인이 default UNL 운영. 각 노드가 자체 UNL 설정 가능하나 대부분 기본 UNL 사용.',
      en: 'Ripple, XRPLF, universities, and individuals operate the default UNL. Each node can set its own UNL but most use the default.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://xrpl.org/docs/concepts/consensus-protocol'],
  },
  {
    chainId: 'algorand',
    nakamotoCoefficient: 13,
    nakamotoNote: {
      ko: 'Pure PoS는 매 라운드 VRF 기반 committee 추첨을 하지만, 참여자별 participation stake 분포로 측정 시 Nakaflow 기준 NC=13.',
      en: 'Pure PoS samples a VRF-based committee each round; measured by participant stake distribution, Nakaflow reports NC=13.',
    },
    activeValidators: 1500,
    validatorCap: null,
    minStake: { ko: '참여 키 등록만 필요 (사실상 0 ALGO 하한)', en: 'Participation key registration only (effectively no ALGO minimum)' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    notes: {
      ko: 'Algorand Foundation과 거래소/재단 관련 지갑이 유의미한 스테이크 보유. 참여 스테이크(participation)는 전체의 일부.',
      en: 'Algorand Foundation and exchange/foundation-affiliated wallets hold a meaningful share. Participation stake is a subset of total supply.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://algoexplorer.io/', 'https://nakaflow.io/'],
  },
  {
    chainId: 'eos',
    nakamotoCoefficient: 8,
    activeValidators: 21,
    validatorCap: 21,
    minStake: { ko: 'EOS 보유자 투표로 선출 (DPoS)', en: 'Elected by EOS-holder votes (DPoS)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    topValidators: [
      { name: 'eosphereiobp', stakeSharePct: 4.8 },
      { name: 'ivote4eosusa', stakeSharePct: 4.78 },
      { name: 'big.one', stakeSharePct: 4.73 },
      { name: 'eostitanprod', stakeSharePct: 4.71 },
      { name: 'newdex.bp', stakeSharePct: 4.67 },
      { name: 'binancestake', stakeSharePct: 4.6 },
      { name: 'eosiodetroit', stakeSharePct: 4.59 },
      { name: 'starteosiobp', stakeSharePct: 4.58 },
      { name: 'eosflytomars', stakeSharePct: 4.54 },
      { name: 'eossupportbp', stakeSharePct: 4.49 },
    ],
    notes: {
      ko: 'Vaulta 리브랜딩 후에도 DPoS 유지. 21 BP + 후보 BP. 초기부터 여러 대형 지갑의 영향력 논란.',
      en: 'DPoS retained after Vaulta rebrand. 21 BPs + candidates. Concerns about large-wallet influence since launch.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://bloks.io/producers'],
  },
  {
    chainId: 'thorchain',
    nakamotoCoefficient: 28,
    activeValidators: 100,
    validatorCap: 100,
    minStake: { ko: '동적 bond 요구량 (현재 ~300K+ RUNE)', en: 'Dynamic bond requirement (~300K+ RUNE currently)' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Node y6yhskf6', stakeSharePct: 1.36 },
      { name: 'Node ztxxnk4j', stakeSharePct: 1.33 },
      { name: 'Node nnxzl9hk', stakeSharePct: 1.3 },
      { name: 'Node 8e3dmw0q', stakeSharePct: 1.27 },
      { name: 'Node 7z8zhcs3', stakeSharePct: 1.27 },
      { name: 'Node 3yyxplcw', stakeSharePct: 1.27 },
      { name: 'Node jm4dk5ey', stakeSharePct: 1.25 },
      { name: 'Node cmn40rde', stakeSharePct: 1.24 },
      { name: 'Node 8dcpkfun', stakeSharePct: 1.24 },
      { name: 'Node 7l3qmaya', stakeSharePct: 1.23 },
    ],
    notes: {
      ko: 'Churn 시스템으로 주기적으로 bottom node 교체. bond의 일부가 churn 대기열에 있음.',
      en: 'Churn system periodically rotates out the weakest nodes. A portion of bonds sits in the churn queue.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://thorchain.net/nodes', 'https://nakaflow.io/'],
  },
  {
    chainId: 'sonic',
    nakamotoCoefficient: 4,
    activeValidators: 45,
    validatorCap: null,
    minStake: { ko: '50K S 셀프 스테이크 + 위임', en: '50K S self-stake + delegation' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    topValidators: [
      { name: 'SonicStrategy CSE.SPTZ OTCQB.DBKSF #2', stakeSharePct: 11.11 },
      { name: 'Tokyo - MAX APR', stakeSharePct: 7.81 },
      { name: 'Sonic Goat 1 - MAX APR', stakeSharePct: 7.43 },
      { name: 'Hyperblocks 2', stakeSharePct: 7.36 },
      { name: 'Sonic Goat 2 - MAX APR', stakeSharePct: 6.42 },
      { name: 'Hyperblocks', stakeSharePct: 6.41 },
      { name: 'Binance Staking', stakeSharePct: 6.4 },
      { name: 'London - MAX APR', stakeSharePct: 5.06 },
      { name: 'SonicLabs', stakeSharePct: 4.68 },
      { name: 'SonicLabs', stakeSharePct: 3.79 },
    ],
    notes: {
      ko: 'Fantom 리브랜딩 후 Lachesis aBFT 계승. 일부 초기 검증자 연속성 유지.',
      en: 'Inherited Lachesis aBFT after Fantom rebrand; some early validator continuity persists.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://explorer.soniclabs.com/validators'],
  },
  {
    chainId: 'tezos',
    nakamotoCoefficient: 4,
    activeValidators: 400,
    validatorCap: null,
    minStake: { ko: '6,000 XTZ (baking rights 최소)', en: '6,000 XTZ minimum (for baking rights)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'Octez (공식), TezEdge, Mavryk 등', en: 'Octez (official), TezEdge, Mavryk, etc.' },
    topValidators: [
      { name: 'Coinbase Baker', stakeSharePct: 15.31 },
      { name: 'Kiln', stakeSharePct: 7.85 },
      { name: 'Everstake', stakeSharePct: 7.28 },
      { name: 'Kraken Baker', stakeSharePct: 6.84 },
      { name: 'tz1eDKeD934e', stakeSharePct: 4.14 },
      { name: 'P2P.org', stakeSharePct: 3.58 },
      { name: 'Tezos Foundation Baker 4', stakeSharePct: 3.4 },
      { name: 'Tezos Foundation Baker 3', stakeSharePct: 3.15 },
      { name: 'tz1cJTktkAEh', stakeSharePct: 3.13 },
      { name: 'Tezos Foundation Baker 2', stakeSharePct: 3.08 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://tzstats.com/bakers'],
  },
  {
    chainId: 'osmosis',
    nakamotoCoefficient: 7,
    activeValidators: 150,
    validatorCap: 150,
    minStake: { ko: '본딩 스테이크로 상위 150 진입 (dynamic)', en: 'Dynamic threshold to enter top 150' },
    permissioning: 'permissionless',
    top33SharePct: 32,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Cosmostation', stakeSharePct: 8.78 },
      { name: 'Inotel', stakeSharePct: 5.82 },
      { name: 'Keplr', stakeSharePct: 5.82 },
      { name: 'Interop', stakeSharePct: 4.66 },
      { name: 'The_Cybernetics', stakeSharePct: 4.13 },
      { name: 'Mendel', stakeSharePct: 3.1 },
      { name: 'Solva (CryptoCrew)', stakeSharePct: 2.6 },
      { name: 'polkachu.com', stakeSharePct: 2.48 },
      { name: 'Stakecito', stakeSharePct: 2.43 },
      { name: ' Lavender.Five Nodes 🐝', stakeSharePct: 2.32 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/osmosis/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'injective',
    nakamotoCoefficient: 6,
    activeValidators: 60,
    validatorCap: 60,
    minStake: { ko: '본딩 스테이크로 상위 60 진입 (dynamic)', en: 'Dynamic threshold to enter top 60' },
    permissioning: 'permissionless',
    top33SharePct: 30,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Zellic', stakeSharePct: 7.85 },
      { name: 'Binance Staking', stakeSharePct: 5.88 },
      { name: 'Kraken', stakeSharePct: 5.57 },
      { name: 'Everstake', stakeSharePct: 5.53 },
      { name: 'Informal Systems', stakeSharePct: 5.14 },
      { name: 'SCV-Security', stakeSharePct: 4.89 },
      { name: 'Injective Foundation', stakeSharePct: 4.22 },
      { name: 'Figment', stakeSharePct: 3.88 },
      { name: 'Cointelegraph Decentralization Guardians', stakeSharePct: 3.43 },
      { name: 'Core ONE', stakeSharePct: 3.27 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/injective/validators'],
  },
  {
    chainId: 'flow',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: '4-role 구조(Collection/Consensus/Execution/Verification)로 단일 NC 정의 어려움. Consensus 노드 ~150개가 핵심.',
      en: '4-role architecture (Collection/Consensus/Execution/Verification); single NC is ambiguous. ~150 consensus nodes are the core.',
    },
    activeValidators: 450,
    validatorCap: null,
    minStake: { ko: '역할별 상이 (Consensus ~250K FLOW, Collection ~250K, Execution ~1.25M, Verification ~135K)', en: 'Varies by role (Consensus ~250K FLOW, Collection ~250K, Execution ~1.25M, Verification ~135K)' },
    permissioning: 'permissionless',
    top33SharePct: null,
    clientDiversity: 'single',
    lastUpdated: '2026-04',
    sourceUrls: ['https://flowscan.io/staking'],
  },
  {
    chainId: 'ronin',
    nakamotoCoefficient: null,
    activeValidators: 22,
    validatorCap: 22,
    minStake: { ko: '250K RON (Standard Validator)', en: '250K RON (Standard Validator)' },
    permissioning: 'hybrid',
    top33SharePct: 40,
    clientDiversity: 'single',
    notes: {
      ko: '12 Governance Validator + 10 Standard Validator 구조. Sky Mavis 연관 노드가 Governance 세트에 상당수 포함.',
      en: '12 Governance Validators + 10 Standard Validators. Sky Mavis-affiliated nodes occupy much of the Governance set.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://app.roninchain.com/validators'],
  },
  {
    chainId: 'kaia',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: 'Council-based IBFT. 49개 Council 중 담합이 ⅓ 초과 시 halt 가능하나, Council 자체가 제한적 심사 기반.',
      en: 'Council-based IBFT. Collusion above ⅓ of 49 Council members could halt consensus, but the Council itself is vetted.',
    },
    activeValidators: 49,
    validatorCap: 49,
    minStake: { ko: '5M KLAY (Council 신청 요건) + 거버넌스 심사', en: '5M KLAY (to apply for Council) + governance review' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: 'Klaytn + Finschia 통합 후 Council 확장 중. 기업/재단 중심.',
      en: 'Expanding Council since the Klaytn + Finschia merger. Enterprise/foundation-centric.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://kaiascan.io/validators'],
  },
  {
    chainId: 'icp',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: 'Permissioned subnet 구조 (Chain Key Cryptography). 전통적 NC 미적용.',
      en: 'Permissioned subnet architecture (Chain Key Cryptography). Traditional NC does not apply.',
    },
    activeValidators: 1000,
    validatorCap: null,
    minStake: { ko: 'NNS 화이트리스트 승인된 노드 제공자만', en: 'Only NNS-whitelisted node providers' },
    permissioning: 'permissioned',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: '~40개 서브넷에 각 13~40개 노드. 각 노드는 서로 다른 데이터센터/국가에 분산 (NNS 정책).',
      en: 'Nodes spread across ~40 subnets (13-40 per subnet), with different data centers/countries per NNS policy.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://dashboard.internetcomputer.org/'],
  },
  {
    chainId: 'neutron',
    nakamotoCoefficient: 6,
    nakamotoNote: {
      ko: 'Cosmos Hub 검증자 세트를 공유 (Interchain Security v1). NC는 Cosmos Hub와 동일.',
      en: 'Shares Cosmos Hub validator set (Interchain Security v1); NC is the same as Cosmos Hub.',
    },
    activeValidators: 180,
    validatorCap: 180,
    minStake: { ko: 'Cosmos Hub 검증자만 참여 가능', en: 'Only Cosmos Hub validators participate' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Cosmostation', stakeSharePct: 6.11 },
      { name: 'polkachu.com', stakeSharePct: 5.64 },
      { name: 'Stakecito', stakeSharePct: 5.61 },
      { name: '01node', stakeSharePct: 5.6 },
      { name: '🐹 Quokka Stake', stakeSharePct: 5.54 },
      { name: 'POSTHUMAN 🧬 StakeDrop', stakeSharePct: 5.54 },
      { name: 'Solva (CryptoCrew)', stakeSharePct: 5.52 },
      { name: 'Hadron', stakeSharePct: 5.51 },
      { name: 'PRO Delegators', stakeSharePct: 5.51 },
      { name: 'SG-1', stakeSharePct: 5.51 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/neutron/validators'],
  },
  {
    chainId: 'polkadot',
    nakamotoCoefficient: null,
    activeValidators: 297,
    validatorCap: 297,
    minStake: { ko: 'Validator: 동적 (~2M DOT). Nominator: ~530 DOT 최소', en: 'Validator: dynamic (~2M DOT). Nominator: ~530 DOT minimum' },
    permissioning: 'permissionless',
    top33SharePct: 33,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'polkadot-sdk (Rust, 공식), Gossamer (Go)', en: 'polkadot-sdk (Rust, official), Gossamer (Go)' },
    notes: {
      ko: 'NPoS는 스테이크를 297개 검증자에 자동 균등 분배하도록 설계되어 NC가 매우 높음.',
      en: 'NPoS is designed to distribute stake evenly across 297 validators, producing a very high NC.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://staking.polkadot.network/', 'https://polkadot.subscan.io/validator'],
  },
  {
    chainId: 'celestia',
    nakamotoCoefficient: 7,
    activeValidators: 100,
    validatorCap: 100,
    minStake: { ko: '본딩 스테이크로 상위 100 진입 (현재 ~1.5M TIA)', en: 'Dynamic threshold to enter top 100 (~1.5M TIA currently)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    topValidators: [
      { name: 'Anchorage Digital', stakeSharePct: 11.36 },
      { name: 'P-OPS Team', stakeSharePct: 4.72 },
      { name: 'BinanceNode', stakeSharePct: 4.2 },
      { name: 'P2P.org 💙', stakeSharePct: 3.54 },
      { name: 'bitcoinsuisse.com', stakeSharePct: 3.37 },
      { name: 'Hex Trust', stakeSharePct: 3.33 },
      { name: 'Qubelabs', stakeSharePct: 3.21 },
      { name: 'Alchemy', stakeSharePct: 2.76 },
      { name: 'Chorus One', stakeSharePct: 2.7 },
      { name: 'Kraken', stakeSharePct: 2.36 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/celestia/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'filecoin',
    nakamotoCoefficient: null,
    activeValidators: 3500,
    validatorCap: null,
    minStake: { ko: '섹터별 pledge collateral (섹터 사이즈별 상이)', en: 'Per-sector pledge collateral (varies by sector size)' },
    permissioning: 'permissionless',
    top33SharePct: 30,
    clientDiversity: 'multi',
    clientDiversityNote: { ko: 'Lotus (공식 Go), Venus, Forest (Rust)', en: 'Lotus (official Go), Venus, Forest (Rust)' },
    lastUpdated: '2026-04',
    sourceUrls: ['https://filscan.io/'],
  },
  {
    chainId: 'initia',
    nakamotoCoefficient: null,
    activeValidators: 50,
    validatorCap: 130,
    minStake: { ko: '본딩 스테이크로 상위 130 진입 (dynamic)', en: 'Dynamic threshold to enter top 130' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    notes: {
      ko: '초기 메인넷 단계로 핵심 팀 연관 검증자가 높은 비중. Minitia (roll-up) 분리.',
      en: 'Early mainnet: core-team-affiliated validators hold a high share. Separate from Minitias (roll-ups).',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://scan.initia.xyz/initiation-2/validators'],
  },
  {
    chainId: 'cosmos-hub',
    nakamotoCoefficient: 4,
    activeValidators: 180,
    validatorCap: 180,
    minStake: { ko: '본딩 스테이크로 상위 180 진입 (현재 ~85K+ ATOM)', en: 'Dynamic threshold to enter top 180 (~85K+ ATOM currently)' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'gaia (Go, 공식) 단일', en: 'Single gaia (Go, official)' },
    topValidators: [
      { name: 'Coinbase01', stakeSharePct: 19.54 },
      { name: 'Upbit Staking', stakeSharePct: 7.1 },
      { name: 'Cosmostation', stakeSharePct: 5.05 },
      { name: 'Kiln', stakeSharePct: 4.63 },
      { name: 'Kraken01', stakeSharePct: 4.33 },
      { name: 'Everstake', stakeSharePct: 3.92 },
      { name: 'Ledger by Chorus One', stakeSharePct: 2.84 },
      { name: 'DokiaCapital', stakeSharePct: 2.78 },
      { name: 'Binance Node', stakeSharePct: 2.65 },
      { name: 'Blockdaemon', stakeSharePct: 2.59 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/cosmos/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'plasma',
    nakamotoCoefficient: null,
    activeValidators: 25,
    validatorCap: null,
    minStake: { ko: '초기 초청 검증자 (세부 미공개)', en: 'Invited validators at launch (details not public)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: '2025년 메인넷 초기 단계. 퍼미션리스 확장 로드맵 있으나 초기에는 Plasma Labs 및 초청 운영자 중심.',
      en: 'Early mainnet (2025) with a roadmap toward permissionless. Initially dominated by Plasma Labs and invited operators.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.plasma.to/faq'],
  },
  {
    chainId: 'flare',
    nakamotoCoefficient: 22,
    activeValidators: 110,
    validatorCap: null,
    minStake: { ko: '1M FLR (FTSO data provider 포함 진입)', en: '1M FLR (including FTSO data providers)' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'Flare 포크 Avalanche Node', en: 'Flare fork of Avalanche Node' },
    topValidators: [
      { name: 'JxfdxuVYR9', stakeSharePct: 2.1 },
      { name: 'tHRbAoCmfv', stakeSharePct: 2.09 },
      { name: 'FVjJ9ScfVU', stakeSharePct: 2.09 },
      { name: 'D4BGLsR7Fa', stakeSharePct: 2.09 },
      { name: 'ekhPu2NYLM', stakeSharePct: 2.09 },
      { name: '1z9XHz5rHU', stakeSharePct: 2.09 },
      { name: 'VNLGbxRtu2', stakeSharePct: 2.09 },
      { name: 'VbUFTP1sLR', stakeSharePct: 2.09 },
      { name: 'LiR1cAkEnN', stakeSharePct: 2.09 },
      { name: '8c75e5USEC', stakeSharePct: 2.02 },
    ],
    lastUpdated: '2026-04',
    sourceUrls: ['https://flaremetrics.io/validators'],
  },
  {
    chainId: 'wemix',
    nakamotoCoefficient: null,
    activeValidators: 40,
    validatorCap: 40,
    minStake: { ko: '1.5M WEMIX (NCP 요건)', en: '1.5M WEMIX (required for NCP)' },
    permissioning: 'hybrid',
    top33SharePct: 33,
    clientDiversity: 'single',
    notes: {
      ko: 'SPoA 40 WONDERS. 각 NCP가 동일 스테이크 요건이라 스테이크 분포는 균등.',
      en: 'SPoA with 40 WONDERS; each NCP has the same stake requirement so distribution is uniform.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.wemix.com/wemix'],
  },
  {
    chainId: 'stable',
    nakamotoCoefficient: null,
    activeValidators: 30,
    validatorCap: null,
    minStake: { ko: '초기 초청 검증자 (세부 미공개)', en: 'Invited validators at launch (details not public)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: '2025년 12월 메인넷. DPoS 전환 로드맵 있으나 현재는 Bitfinex/Tether 연관 운영자 중심.',
      en: 'Mainnet Dec 2025, with a DPoS roadmap. Currently dominated by Bitfinex/Tether-affiliated operators.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.stable.xyz/whitepaper.pdf'],
  },
  {
    chainId: 'tempo',
    nakamotoCoefficient: null,
    activeValidators: 15,
    validatorCap: null,
    minStake: { ko: '해당 없음 (퍼미션드 · 초청제)', en: 'N/A (permissioned, invite-only)' },
    permissioning: 'permissioned',
    top33SharePct: null,
    clientDiversity: 'single',
    clientDiversityNote: { ko: 'Reth 기반 EVM, 자체 Simplex BFT', en: 'Reth-based EVM with proprietary Simplex BFT' },
    notes: {
      ko: '2026.03.18 메인넷 이후에도 core team + 초청 파트너(Visa, Mastercard, OpenAI, Anthropic 등)로 운영. 단계적 탈중앙화 로드맵.',
      en: 'Even post-mainnet (Mar 18, 2026), operated by the core team plus invited partners (Visa, Mastercard, OpenAI, Anthropic, etc.). Progressive-decentralization roadmap.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.tempo.xyz/'],
  },
  {
    chainId: 'citrea',
    nakamotoCoefficient: null,
    activeValidators: 1,
    validatorCap: null,
    minStake: { ko: '해당 없음 (초기 단일 sequencer)', en: 'N/A (initial single sequencer)' },
    permissioning: 'hybrid',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: 'Bitcoin ZK 롤업. 초기 단일 sequencer, multi-sequencer 전환 로드맵. BitVM 기반 챌린지로 사기 방지.',
      en: 'Bitcoin ZK rollup with an initial single sequencer and a multi-sequencer roadmap. BitVM-based challenges guard against fraud.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.citrea.xyz/'],
  },
  {
    chainId: 'astar',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: 'Polkadot 파라체인 collator 구조 + 릴레이 체인 검증자 상속. Collator ~50, 실질 확정성은 Polkadot에 의존.',
      en: 'Polkadot-parachain collators + inherited relay validators. ~50 collators; finality depends on Polkadot.',
    },
    activeValidators: 50,
    validatorCap: null,
    minStake: { ko: '3.2M ASTR (Collator 본드)', en: '3.2M ASTR (Collator bond)' },
    permissioning: 'permissionless',
    top33SharePct: null,
    clientDiversity: 'single',
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.astar.network/docs/build/nodes/collator/learn/'],
  },
  {
    chainId: 'supra',
    nakamotoCoefficient: null,
    activeValidators: 100,
    validatorCap: null,
    minStake: { ko: '55K SUPRA 최소 셀프 본딩', en: '55K SUPRA minimum self-bond' },
    permissioning: 'permissionless',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: 'Tribes & Clans 구조: 전체 노드를 지역별 Clan으로 분할 후 Moonshot BFT 수행.',
      en: 'Tribes & Clans structure: nodes split into regional Clans, then run Moonshot BFT.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.supra.com/'],
  },
  {
    chainId: 'somnia',
    nakamotoCoefficient: null,
    activeValidators: 60,
    validatorCap: null,
    minStake: { ko: '5M SOMI', en: '5M SOMI' },
    permissioning: 'permissionless',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: '메인넷 초기 단계. MultiStream 구조상 각 검증자가 독립 data chain을 운영.',
      en: 'Early mainnet. MultiStream architecture gives each validator an independent data chain.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.somnia.network/'],
  },
  {
    chainId: 'mantra',
    nakamotoCoefficient: null,
    activeValidators: 50,
    validatorCap: 100,
    minStake: { ko: '본딩 스테이크로 상위 100 진입 (dynamic)', en: 'Dynamic threshold to enter top 100' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    notes: {
      ko: 'RWA 특화 Cosmos SDK. 2025년 OM 대형 다운 이후 투자자/거래소 영향력 논란.',
      en: 'RWA-focused Cosmos SDK chain. Concerns about investor/exchange influence after the 2025 OM drawdown.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.mintscan.io/mantra/validators'],
  },
  {
    chainId: 'story',
    nakamotoCoefficient: 4,
    activeValidators: 80,
    validatorCap: 100,
    minStake: { ko: '본딩 스테이크로 상위 100 진입 (dynamic)', en: 'Dynamic threshold to enter top 100' },
    permissioning: 'permissionless',
    top33SharePct: 35,
    clientDiversity: 'single',
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.storyscan.xyz/validators', 'https://nakaflow.io/'],
  },
  {
    chainId: 'zetachain',
    nakamotoCoefficient: null,
    activeValidators: 100,
    validatorCap: 100,
    minStake: { ko: '본딩 스테이크로 상위 100 진입 (dynamic)', en: 'Dynamic threshold to enter top 100' },
    permissioning: 'permissionless',
    top33SharePct: 40,
    clientDiversity: 'single',
    notes: {
      ko: 'Core validator + Observer-Signer(TSS) 이중 역할. TSS 서명자는 core validator에 연결.',
      en: 'Dual role: Core validators + Observer-Signers (TSS). TSS signers are paired with core validators.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://www.zetachain.com/docs/about/token-utility/validators/'],
  },
  {
    chainId: 'vana',
    nakamotoCoefficient: null,
    activeValidators: 64,
    validatorCap: 128,
    minStake: { ko: '35K VANA (L1 Validator)', en: '35K VANA (L1 Validator)' },
    permissioning: 'permissionless',
    top33SharePct: null,
    clientDiversity: 'single',
    notes: {
      ko: 'L1 Validator 64 → 128 확장 중. Satya Validator (TEE 기반 데이터 검증자)는 별도.',
      en: 'L1 Validators expanding from 64 to 128. Satya Validators (TEE-based data validators) are separate.',
    },
    lastUpdated: '2026-04',
    sourceUrls: ['https://docs.vana.org/'],
  },
  {
    chainId: 'canton',
    nakamotoCoefficient: null,
    nakamotoNote: {
      ko: 'Permissioned 2/3 BFT 구조로 스테이크 기반 합의가 아님. 전통적 NC 정의가 적용되지 않습니다.',
      en: 'Permissioned 2/3 BFT without stake-based consensus; the traditional NC definition does not apply.',
    },
    activeValidators: 42,
    validatorCap: null,
    minStake: {
      ko: '해당 없음 (GSF 초대 기반 · 기관 심사)',
      en: 'N/A (GSF invitation with institutional vetting)',
    },
    permissioning: 'permissioned',
    top33SharePct: null,
    clientDiversity: 'single',
    clientDiversityNote: {
      ko: 'Digital Asset의 Canton 프로토콜 단일 구현 (DAML 기반)',
      en: 'Single Digital Asset Canton protocol implementation (DAML-based)',
    },
    notes: {
      ko: 'Cumberland, Five North, MPC-Holding, Coin Metrics, Kiln, Hypernative 등 기관 운영자가 Super Validator 노드를 운영합니다. 전 노드가 모든 Canton Coin 전송을 2/3 BFT로 검증하며, GSF(Linux Foundation 파트너십)가 거버넌스를 조율.',
      en: 'Institutional operators such as Cumberland, Five North, MPC-Holding, Coin Metrics, Kiln, and Hypernative run Super Validator nodes. All nodes validate every Canton Coin transfer via 2/3 BFT, with the GSF (Linux Foundation partnership) coordinating governance.',
    },
    lastUpdated: '2026-04',
    sourceUrls: [
      'https://www.canton.network/global-synchronizer',
      'https://www.cantonscan.com/supervalidators',
      'https://www.kiln.fi/protocols/canton',
    ],
  },
];

export function getDecentralization(chainId: string): DecentralizationData | undefined {
  return DECENTRALIZATION.find((d) => d.chainId === chainId);
}
